-- TESTS/tasks/tasks_index_spec.lua -- tasks.index: render, write-only-when-different, check, global text.

return function(H)
  local eq, ok = H.eq, H.ok
  local uv = vim.uv or vim.loop
  local F = dofile(vim.fs.dirname(debug.getinfo(1, "S").source:sub(2)) .. "/fixture.lua")
  local index = require("tasks_nvim.index")
  local model = require("tasks_nvim.model")
  local scan = require("tasks_nvim.scan")

  --- A task record parsed from fixture text, as if found in `<area>/ROADMAP/tasks/<slug>.md`.
  ---@param area string
  ---@param slug string
  ---@param meta table[]
  ---@param body? string
  local function task(area, slug, meta, body)
    return model.parse_text(F.text(meta, body), {
      path = "/v/" .. area .. "/ROADMAP/tasks/" .. slug .. ".md",
      area = area,
    })
  end

  local MARK = "<!-- GENERATED by tasks.nvim (:Tasks index) — do not edit; edit tasks/*.md -->"

  local alpha = task(
    "lib.nvim",
    "alpha",
    F.meta("Alpha", "doing", { { "prio", "1" }, { "effort", "M" } }),
    "\nFirst thing.\n"
  )
  local beta = task(
    "lib.nvim",
    "beta",
    F.meta('"Beta | pipe"', "open", { { "prio", "2" }, { "effort", "S" } }),
    "\nHas a | pipe and [brackets].\n"
  )
  local gamma = task(
    "lib.nvim",
    "gamma",
    F.meta("Gamma", "decision", { { "summary", "wartet auf Entscheidung" } }),
    ""
  )
  local delta = task(
    "lib.nvim",
    "delta",
    F.meta("Delta", "blocked", { { "prio", "2" }, { "blocked_by", "cascade.nvim/x" } }),
    "\nBlocked summary.\n"
  )
  local eps = task("lib.nvim", "eps", F.meta("Eps", "parked"), "")

  -- ── render: the exact bytes ─────────────────────────────────────────────
  local expected = table.concat({
    MARK,
    "# lib.nvim — offene Tasks (5)",
    "",
    "| Status | Prio | Effort | Task | Zusammenfassung |",
    "|---|---|---|---|---|",
    "| doing | 1 | M | [Alpha](tasks/alpha.md) | First thing. |",
    "| decision | – | – | [Gamma](tasks/gamma.md) | wartet auf Entscheidung |",
    "| blocked | 2 | – | [Delta](tasks/delta.md) | Blocked summary. (blockiert durch `cascade.nvim/x`) |",
    "| open | 2 | S | [Beta \\| pipe](tasks/beta.md) | Has a \\| pipe and [brackets]. |",
    "| parked | – | – | [Eps](tasks/eps.md) | – |",
    "",
  }, "\n")
  local text, n = index.render("lib.nvim", { alpha, beta, gamma, delta, eps })
  eq(n, 5)
  eq(text, expected, "index text matches concept section 4.1")

  -- same bytes whatever the order the tasks come in
  local variants = {
    { eps, delta, gamma, beta, alpha },
    { beta, eps, alpha, gamma, delta },
    { gamma, alpha, eps, beta, delta },
  }
  for i, v in ipairs(variants) do
    eq(index.render("lib.nvim", v), expected, "deterministic, input order " .. i)
  end
  eq(index.render("lib.nvim", { alpha, beta, gamma, delta, eps }), expected, "twice, same bytes")

  -- only open tasks of ROADMAP/tasks are listed
  local done = task("lib.nvim", "finished", F.meta("Finished", "done"))
  local unknown = task("lib.nvim", "weird", F.meta("Weird", "wip"))
  local nostatus = task("lib.nvim", "nostatus", { { "title", "No status" } })
  local filed = model.parse_text(F.text(F.meta("In backlog", "open")), {
    path = "/v/lib.nvim/Backlog/TASKS/2026-01-01_in-backlog.md",
    area = "lib.nvim",
    location = "backlog",
  })
  local only = index.render("lib.nvim", { alpha, done, unknown, nostatus, filed })
  ok(only:find("# lib.nvim — offene Tasks (1)", 1, true), "count only the open one")
  ok(not only:find("finished", 1, true) and not only:find("weird", 1, true))
  ok(not only:find("in-backlog", 1, true), "Backlog tasks are not listed")

  local nothing, zero = index.render("lib.nvim", { done, unknown, nostatus })
  eq(nothing, nil, "nothing open: no text")
  eq(zero, 0)
  eq((index.render("lib.nvim", {})), nil)

  -- escaping and truncation
  local tricky =
    task("lib.nvim", "tricky", F.meta('"[WIP] a | b"', "open"), "\n" .. ("long "):rep(60) .. "\n")
  local tricky_text = index.render("lib.nvim", { tricky })
  ok(
    tricky_text:find("[\\[WIP\\] a \\| b](tasks/tricky.md)", 1, true),
    "brackets and pipe escaped in the link text"
  )
  local row = tricky_text:match("[^\n]*tricky%.md[^\n]*")
  local summary_cell = row:match("%| ([^|]*) %|$")
  ok(summary_cell:find("…$"), "a long summary is cut with an ellipsis")
  eq(vim.fn.strchars(summary_cell), index.MAX_SUMMARY, "cut at MAX_SUMMARY characters")
  local short = index.render("lib.nvim", { tricky }, { max_summary = 10 })
  ok(short:find("long long…", 1, true), "max_summary option")
  -- every table row has the same number of columns (what md_lint checks)
  for line in expected:gmatch("[^\n]+") do
    if line:sub(1, 1) == "|" then
      local stripped = line:gsub("\\|", "")
      local _, cols = stripped:gsub("|", "")
      eq(cols, 6, "6 pipes = 5 columns in: " .. line)
    end
  end
  local spaced = task("lib.nvim", "has space", F.meta("Odd", "open"))
  ok(
    index.render("lib.nvim", { spaced }):find("(tasks/has%20space.md)", 1, true),
    "link target is percent-encoded"
  )

  -- a backslash in a title must not undo the escaping of the brackets next to it:
  -- `\\[` is an escaped backslash followed by a LIVE bracket, so a title like
  -- `\[x\](http://evil)` used to turn into a real link in the rendered index.
  do
    ---@param title string  the title's text; written as a double-quoted YAML value
    ---@return string link_text  what sits between `[` and `](tasks/esc.md)` in the row
    local function link_text_of(title)
      local quoted = '"' .. title:gsub("\\", "\\\\") .. '"'
      local rendered = index.render("lib.nvim", { task("lib.nvim", "esc", F.meta(quoted, "open")) })
      local line = rendered:match("[^\n]*esc%.md[^\n]*")
      return line:match("%| %[(.*)%]%(tasks/esc%.md%) %|")
    end

    --- The number of backslashes directly in front of position `i` of `s`.
    local function slashes_before(s, i)
      local count = 0
      while i - count - 1 >= 1 and s:sub(i - count - 1, i - count - 1) == "\\" do
        count = count + 1
      end
      return count
    end

    --- A bracket is escaped (cannot open or close a link) when an odd number of
    --- backslashes precedes it, as in CommonMark.
    local function all_brackets_escaped(s)
      for i = 1, #s do
        local c = s:sub(i, i)
        if (c == "[" or c == "]") and slashes_before(s, i) % 2 == 0 then
          return false
        end
      end
      return true
    end

    local evil = link_text_of("\\[x\\](http://evil.example)")
    ok(all_brackets_escaped(evil), "no live bracket in: " .. evil)
    eq(evil, "\\\\\\[x\\\\\\](http://evil.example)", "each run is doubled, then the escape")

    eq(link_text_of("[WIP] a"), "\\[WIP\\] a", "a title without backslashes is escaped as before")
    eq(link_text_of("C:\\dir\\file"), "C:\\dir\\file", "a backslash before a letter is as written")

    local trailing = link_text_of("ends with a backslash \\")
    eq(trailing, "ends with a backslash \\\\", "a trailing backslash is doubled")
    ok(slashes_before(trailing .. "]", #trailing + 1) % 2 == 0, "the closing ] stays unescaped")

    local mixed = link_text_of("a\\\\[b]\\")
    ok(all_brackets_escaped(mixed), "runs of two backslashes too: " .. mixed)
    ok(slashes_before(mixed .. "]", #mixed + 1) % 2 == 0, "and at the end: " .. mixed)

    -- a pipe next to a backslash still leaves the row at five columns
    local piped =
      index.render("lib.nvim", { task("lib.nvim", "pipe", F.meta('"a\\\\| b"', "open")) })
    local _, pipes = piped:match("[^\n]*pipe%.md[^\n]*"):gsub("\\|", ""):gsub("|", "")
    eq(pipes, 6, "6 pipes = 5 columns")
  end

  -- a control character in any cell (a record that did not come through the
  -- parser, or a future field) is not written into the generated file
  do
    local raw = task("lib.nvim", "raw", F.meta("Raw", "open"))
    raw.title = "a\27[2Jb\r\nc|d"
    raw.summary = "s\27]52;c;AAAA\7e"
    raw.effort = "M\27"
    local rendered = index.render("lib.nvim", { raw })
    ok(not rendered:find("[\1-\9\11-\31\127]"), "no control character but the line breaks")
    eq(
      rendered:match("[^\n]*raw%.md[^\n]*"),
      "| open | – | M  | [a \\[2Jb c\\|d](tasks/raw.md) | s ]52;c;AAAA e |",
      "controls became spaces, a CR LF pair one space"
    )
  end

  -- a file name that is no valid slug still gets a row that parses and a target
  -- that cannot end the link early or add a column
  do
    local odd = task("lib.nvim", 'a|b[c](d) e<f>g`h"i#j%k', F.meta("Odd name", "open"))
    local line = index.render("lib.nvim", { odd }):match("[^\n]*Odd name[^\n]*")
    ok(line:find("(tasks/a%7Cb%5Bc%5D%28d%29%20e%3Cf%3Eg%60h%22i%23j%25k.md)", 1, true), line)
    local _, pipes = line:gsub("\\|", ""):gsub("|", "")
    eq(pipes, 6, "the pipe in the file name did not add a column")
  end

  -- ── write_area / check ──────────────────────────────────────────────────
  local root = F.vault(H)
  F.task(H, root, "lib.nvim", "alpha", F.meta("Alpha", "doing", { { "prio", "1" } }), "\nFirst.\n")
  F.task(H, root, "lib.nvim", "beta", F.meta("Beta", "open", { { "prio", "2" } }), "\nSecond.\n")
  local path = root .. "/lib.nvim/ROADMAP/TASKS.md"
  local opts = { root = root }

  local stale = index.write_area("lib.nvim", { root = root, check = true })
  eq(stale.action, "stale")
  eq(stale.reason, "missing")
  ok(not H.exists(path), "check mode writes nothing")

  local r1 = index.write_area("lib.nvim", opts)
  eq(r1.action, "written")
  eq(r1.open, 2)
  eq(r1.path, path)
  local written = H.read(path)
  ok(written:find("# lib.nvim — offene Tasks (2)", 1, true))
  ok(not written:find("\r", 1, true), "LF line endings")
  ok(written:sub(-1) == "\n" and written:sub(-2, -2) ~= "\n", "ends with exactly one newline")

  -- unchanged: no write at all (an old mtime survives)
  assert(uv.fs_utime(path, 1000000000, 1000000000))
  local r2 = index.write_area("lib.nvim", opts)
  eq(r2.action, "unchanged")
  eq(uv.fs_stat(path).mtime.sec, 1000000000, "an unchanged index is not rewritten")
  eq(H.read(path), written)
  eq(
    index.write_area("lib.nvim", { root = root, check = true }).action,
    "unchanged",
    "check: fresh"
  )

  -- a task change makes it stale, then fresh again
  F.task(H, root, "lib.nvim", "beta", F.meta("Beta", "doing", { { "prio", "1" } }), "\nSecond.\n")
  local outdated = index.write_area("lib.nvim", { root = root, check = true })
  eq(outdated.action, "stale")
  eq(outdated.reason, "outdated")
  eq(H.read(path), written, "check did not touch the file")
  eq(index.write_area("lib.nvim", opts).action, "written")
  ok(H.read(path):find("| doing | 1 | – | [Beta](tasks/beta.md) | Second. |", 1, true))

  -- a hand edit (e.g. someone "fixed" the table) is caught and overwritten
  H.write(path, H.read(path) .. "\nhand-written line\n")
  eq(index.write_area("lib.nvim", { root = root, check = true }).reason, "outdated")
  eq(index.write_area("lib.nvim", opts).action, "written")
  ok(not H.read(path):find("hand-written", 1, true))

  -- CRLF checkout: equal content is fresh and untouched; changed content stays CRLF
  local lf_text = H.read(path)
  H.write(path, H.crlf(lf_text))
  assert(uv.fs_utime(path, 1000000000, 1000000000))
  eq(
    index.write_area("lib.nvim", { root = root, check = true }).action,
    "unchanged",
    "CRLF index counts as fresh"
  )
  eq(index.write_area("lib.nvim", opts).action, "unchanged")
  eq(uv.fs_stat(path).mtime.sec, 1000000000, "CRLF index is left alone")
  F.task(H, root, "lib.nvim", "gamma", F.meta("Gamma", "open"), "\nThird.\n")
  eq(index.write_area("lib.nvim", opts).action, "written")
  local crlf_after = H.read(path)
  ok(crlf_after:find("\r\n", 1, true), "the CRLF style is kept")
  ok(not crlf_after:gsub("\r\n", ""):find("\n", 1, true), "no bare LF mixed in")
  ok(crlf_after:find("Gamma", 1, true))

  -- last open task gone: the stale file is removed
  for _, slug in ipairs({ "alpha", "beta", "gamma" }) do
    vim.fn.delete(root .. "/lib.nvim/ROADMAP/tasks/" .. slug .. ".md")
  end
  local orphan = index.write_area("lib.nvim", { root = root, check = true })
  eq(orphan.action, "stale")
  eq(orphan.reason, "orphan")
  ok(H.exists(path), "check keeps the orphan")
  local removed = index.write_area("lib.nvim", opts)
  eq(removed.action, "removed")
  eq(removed.open, 0)
  ok(not H.exists(path), "no TASKS.md for an area without open tasks")
  eq(index.write_area("lib.nvim", opts).action, "unchanged", "nothing to remove the second time")

  -- an area with only done / unreadable-status tasks has no index either
  F.task(H, root, "cascade.nvim", "was-done", F.meta("Was done", "done"))
  eq(index.write_area("cascade.nvim", opts).action, "unchanged")
  ok(not H.exists(root .. "/cascade.nvim/ROADMAP/TASKS.md"))

  -- a directory that cannot be listed is an error, never a wrong index
  local nores, nerr = index.write_area("no-such-area/../x", opts)
  eq(nores, nil)
  ok(nerr)

  -- ── write_all ───────────────────────────────────────────────────────────
  F.task(H, root, "lib.nvim", "one", F.meta("One", "open"))
  F.task(H, root, "ALL", "cross", F.meta("Cross", "decision"))
  local results, errors = index.write_all(opts)
  eq(errors, {})
  local actions = {}
  for _, r in ipairs(results) do
    actions[r.area] = r.action
  end
  eq(actions, {
    ALL = "written",
    ["cascade.nvim"] = "unchanged",
    ["lib.nvim"] = "written",
    ["migrate.nvim"] = "unchanged",
    ["nvim-config"] = "unchanged",
  }, "every area, areas sorted")
  local again = index.write_all(opts)
  for _, r in ipairs(again) do
    eq(r.action, "unchanged", "second run changes nothing: " .. r.area)
  end
  local checked, check_errors = index.write_all({ root = root, check = true })
  eq(check_errors, {})
  for _, r in ipairs(checked) do
    eq(r.action, "unchanged", "check after write: " .. r.area)
  end

  local subset = index.write_all({ root = root, areas = { "lib.nvim" } })
  eq(#subset, 1)

  -- best effort: one area failing does not stop the others (here: its TASKS.md is a directory)
  vim.fn.delete(root .. "/lib.nvim/ROADMAP/TASKS.md")
  vim.fn.mkdir(root .. "/lib.nvim/ROADMAP/TASKS.md", "p")
  F.task(H, root, "ALL", "second", F.meta("Second", "open"))
  local partial, partial_errors = index.write_all(opts)
  eq(#partial_errors, 1, "the failing area is reported")
  ok(partial_errors[1]:find("lib.nvim", 1, true))
  local seen = {}
  for _, r in ipairs(partial) do
    seen[r.area] = r.action
  end
  eq(seen.ALL, "written", "the other areas were still processed")
  vim.fn.delete(root .. "/lib.nvim/ROADMAP/TASKS.md", "rf")

  -- ── global text ─────────────────────────────────────────────────────────
  local g_alpha = task(
    "lib.nvim",
    "alpha",
    F.meta("Alpha", "doing", { { "prio", "1" }, { "effort", "M" }, { "updated", "2026-10-01" } }),
    "\nFirst thing.\n"
  )
  local g_beta = task(
    "lib.nvim",
    "beta",
    F.meta("Beta", "open", { { "prio", "2" }, { "effort", "S" }, { "created", "2026-09-01" } }),
    "\nSecond.\n"
  )
  local g_gamma = task(
    "cascade.nvim",
    "gamma",
    F.meta("Gamma", "decision", { { "updated", "2026-08-15" } }),
    "\nWaiting.\n"
  )
  local g_done = task("lib.nvim", "gone", F.meta("Gone", "done"))
  local global, open_count = index.render_global(
    { g_beta, g_gamma, g_alpha, g_done },
    { areas = { "ALL", "cascade.nvim", "lib.nvim" } }
  )
  eq(open_count, 3)
  eq(
    global,
    table.concat({
      "<!-- GENERATED on demand (:Tasks list all --to=file:...) — never committed, do not edit; edit tasks/*.md -->",
      "# Offene Tasks — alle Bereiche (3 in 2 Bereichen)",
      "",
      "## Pro Bereich",
      "",
      "| Bereich | doing | decision | blocked | open | parked | Gesamt | Prio | Ältester Stand |",
      "|---|---|---|---|---|---|---|---|---|",
      "| [ALL](../ALL/ROADMAP/TASKS.md) | 0 | 0 | 0 | 0 | 0 | 0 | – | – |",
      "| [cascade.nvim](../cascade.nvim/ROADMAP/TASKS.md) | 0 | 1 | 0 | 0 | 0 | 1 | – | 2026-08-15 |",
      "| [lib.nvim](../lib.nvim/ROADMAP/TASKS.md) | 1 | 0 | 0 | 1 | 0 | 2 | 1 | 2026-09-01 |",
      "",
      "## Top 3",
      "",
      "| Status | Prio | Effort | Bereich | Task | Zusammenfassung |",
      "|---|---|---|---|---|---|",
      "| doing | 1 | M | lib.nvim | [Alpha](../lib.nvim/ROADMAP/tasks/alpha.md) | First thing. |",
      "| decision | – | – | cascade.nvim | [Gamma](../cascade.nvim/ROADMAP/tasks/gamma.md) | Waiting. |",
      "| open | 2 | S | lib.nvim | [Beta](../lib.nvim/ROADMAP/tasks/beta.md) | Second. |",
      "",
    }, "\n"),
    "the global overview, exact bytes"
  )
  local without = index.render_global({ g_beta, g_gamma, g_alpha }, { top = 1, links = false })
  ok(without:find("## Top 1", 1, true), "top option")
  ok(not without:find("](", 1, true), "links = false: no links")
  ok(not without:find("| ALL |", 1, true), "areas without tasks are only listed when asked for")
  eq(
    index.render_global({ g_beta, g_gamma, g_alpha }, { top = 1, links = false }),
    without,
    "deterministic"
  )
  ok(
    index
      .render_global({ g_alpha }, { link_prefix = "../../" })
      :find("](../../lib.nvim/ROADMAP/TASKS.md)", 1, true)
  )
  local empty_global, empty_n = index.render_global({}, {})
  eq(empty_n, 0)
  ok(empty_global:find("(0 in 0 Bereichen)", 1, true))

  -- nothing in the engine ever writes ALL/TASKS.md (decision E2)
  ok(not H.exists(root .. "/ALL/TASKS.md"), "ALL/TASKS.md was never written")
  local scanned = scan.all({ root = root })
  index.render_global(scanned, {})
  ok(not H.exists(root .. "/ALL/TASKS.md"), "rendering the global text writes nothing")
end
