-- TESTS/tasks_plan_cli_spec.lua -- the headless verbs over the plan: `plan`, `next`, `estimate`, `list --ready|--waiting`
-- and the lines `done` prints about what it freed and what comes next.

---@diagnostic disable: need-check-nil
-- Why: a value is bound with assert()/ok() in the same body, so a nil fails the spec at that line.

return function(H)
  local eq, ok, has, lacks = H.eq, H.ok, H.has, H.lacks
  local F = dofile(vim.fs.dirname(debug.getinfo(1, "S").source:sub(2)) .. "/fixture.lua")
  local cli = require("tasks_nvim.cli")
  local mutate = require("tasks_nvim.mutate")

  local root = F.vault(H)
  local o = { root = root, today = F.TODAY, checkpoint_dir = H.tmpdir() .. "/cp" }
  local common = { "--vault=" .. root, "--today=" .. F.TODAY }

  ---@param argv string[]
  ---@return { code: integer, out: string, err: string }
  local function run(argv)
    local out, err = {}, {}
    local args = vim.list_extend(vim.deepcopy(argv), common)
    local code = cli.run(args, {
      out = function(t)
        out[#out + 1] = t
      end,
      err = function(t)
        err[#err + 1] = t
      end,
    })
    return { code = code, out = table.concat(out), err = table.concat(err) }
  end

  ---@param r { out: string }
  ---@return string[]
  local function lines(r)
    local text = r.out:gsub("\n$", "")
    return text == "" and {} or vim.split(text, "\n", { plain = true })
  end

  ---@param area string
  ---@param title string
  ---@param extra? table
  ---@return string id
  local function new(area, title, extra)
    local res = assert(mutate.new(area, vim.tbl_extend("force", o, { title = title }, extra or {})))
    return res.id
  end

  -- A small vault: a chain in lib.nvim, a decision that unlocks it, one task in cascade.nvim waiting on the chain's
  -- head across areas, and one that is for an AI session.
  local base = new("lib.nvim", "Plan base", { prio = 2, effort = "S", value = 4 })
  local mid = new("lib.nvim", "Plan mid", { prio = 2, effort = "M", value = 3 })
  local top = new("lib.nvim", "Plan top", { prio = 1, effort = "L", value = 5 })
  local decide = new("lib.nvim", "Plan decide", { status = "decision" })
  local cross = new("cascade.nvim", "Plan cross", { effort = "XS" })
  local ai = new("cascade.nvim", "Plan ai", { actor = "cdx", prio = 1, effort = "S", value = 5 })
  assert(mutate.set(mid, { blocked_by = "[" .. base .. "]" }, o))
  assert(mutate.set(top, { blocked_by = "[" .. mid .. "," .. decide .. "]" }, o))
  assert(mutate.set(cross, { blocked_by = "[" .. base .. "]" }, o))

  -- ── list --ready / --waiting: one definition, judged against the whole vault ──
  local ready = run({ "list", "--ready", "--format=ids" })
  eq(ready.code, 0, ready.err)
  local ready_ids = lines(ready)
  ok(vim.tbl_contains(ready_ids, base), "nothing blocks the base")
  ok(
    vim.tbl_contains(ready_ids, decide),
    "a decision is ready: it waits for the human, not for a task"
  )
  ok(not vim.tbl_contains(ready_ids, mid), "mid waits on the base")
  ok(not vim.tbl_contains(ready_ids, cross), "a blocker in ANOTHER area counts")
  local waiting = run({ "list", "--waiting", "--format=ids" })
  local waiting_ids = lines(waiting)
  ok(vim.tbl_contains(waiting_ids, mid))
  ok(vim.tbl_contains(waiting_ids, top))
  ok(vim.tbl_contains(waiting_ids, cross))
  ok(not vim.tbl_contains(waiting_ids, base))
  -- narrowing to one area must not lose the cross-area blocker
  local scoped = lines(run({ "list", "cascade.nvim", "--waiting", "--format=ids" }))
  eq(scoped, { cross }, "cross waits on lib.nvim/plan-base even when only cascade.nvim is listed")
  local both = run({ "list", "--ready", "--waiting" })
  eq(both.code, 2)
  has(both.err, "exclude each other")

  -- ── list --unestimated ──
  local unest = lines(run({ "list", "--unestimated", "--format=ids" }))
  ok(vim.tbl_contains(unest, decide), "no effort, no value")
  ok(vim.tbl_contains(unest, cross), "an effort but no value")
  ok(not vim.tbl_contains(unest, base), "both numbers: estimated")

  -- ── plan ──
  local md = run({ "plan", "lib.nvim" })
  eq(md.code, 0, md.err)
  has(md.out, "<!-- GENERATED by `tasks plan` -- do not edit -->")
  has(md.out, "# Plan: lib.nvim -- " .. F.TODAY)
  has(md.out, "## Ready now")
  has(md.out, "## Decisions by leverage")
  has(md.out, "## Stage 0")
  has(md.out, "## Stage 2")
  has(md.out, "## Critical path")
  has(md.out, "estimate from the scale, not a promise")
  has(md.out, base)

  local tsv = lines(run({ "plan", "lib.nvim", "--format=tsv" }))
  eq(tsv[1]:match("^(%d+)\t([^\t]+)\t"), "0", "stage first")
  local last = vim.split(tsv[#tsv], "\t", { plain = true })
  eq(last[2], top, "the chain ends with the task that waits on the most")
  eq(last[1], "2")
  eq(last[3], "waiting")

  eq(
    lines(run({ "plan", "lib.nvim", "--format=ids", "--ready" })),
    { decide, base },
    "plan order: a decision before an open task (`next` ranks the other way round)"
  )
  eq(
    lines(run({ "plan", "--for=" .. top, "--format=ids" })),
    { decide, base, mid, top },
    "the task and everything before it"
  )
  local cross_for = lines(run({ "plan", "--for=" .. cross, "--format=ids" }))
  eq(cross_for, { base, cross }, "--for crosses areas")

  local bad = run({ "plan", "--for=lib.nvim/nothing" })
  eq(bad.code, 1)
  has(bad.err, "no such open task")
  eq(run({ "plan", "--format=pdf" }).code, 2)
  eq(run({ "plan", "nope.nvim" }).code, 2)
  eq(run({ "plan", "lib.nvim", "cascade.nvim" }).code, 2)

  -- filters narrow the scope like they do for list
  local filtered = lines(run({ "plan", "--status=decision", "--format=ids" }))
  eq(filtered, { decide })

  -- ── estimate ──
  local est = run({ "estimate", "lib.nvim" })
  eq(est.code, 0, est.err)
  local first = lines(est)[1]
  has(first, "4 tasks")
  has(first, "from 3 of 4")
  has(first, "value 12")
  has(first, "estimate from the scale, not a promise")
  has(est.out, "unestimated: 1")
  local wins = run({ "estimate", "cascade.nvim" })
  has(wins.out, "quick wins: " .. ai, "value 5 and effort S is a quick win")
  eq(run({ "estimate", "--for=" .. top }).code, 0)

  -- ── next ──
  local nxt = run({ "next", "lib.nvim" })
  eq(nxt.code, 0, nxt.err)
  local n_lines = lines(nxt)
  has(n_lines[1], "next: " .. base, "the base: it frees the most")
  has(n_lines[1], "area", "and the reason is the area ranking")
  local with_ai = run({ "next" })
  has(with_ai.out, "cdx: " .. ai, "the AI task is listed apart ...")
  lacks(lines(with_ai)[1], ai, "... and is never 'your next task'")
  local queue = lines(run({ "next", "--actor=cdx" }))
  has(queue[1], "next: " .. ai, "--actor=cdx asks for the AI queue")
  eq(run({ "next", "--actor=robot" }).code, 2)
  eq(run({ "next", "--n=0" }).code, 2)
  local three = lines(run({ "next", "--n=3" }))
  local thens = 0
  for _, l in ipairs(three) do
    if l:find("^then:") then
      thens = thens + 1
    end
  end
  eq(thens, 1, "--n=3 asks for three, but only two tasks are startable for the human")
  local solo = lines(run({ "next", "--n=1" }))
  ok(#solo >= 1 and not solo[1]:find("then:"), "--n=1: the best only")
  for _, l in ipairs(solo) do
    lacks(l, "then:")
  end

  -- ── done prints what it freed and what comes next ──
  local fin = run({ "done", base })
  eq(fin.code, 0, fin.err)
  has(fin.out, "done\t" .. base)
  has(fin.out, "freed: ")
  has(fin.out, mid)
  has(fin.out, cross)
  has(fin.out, "next: ")
  local quiet = run({ "done", mid, "--no-next" })
  eq(quiet.code, 0, quiet.err)
  lacks(quiet.out, "next:", "--no-next silences it")
  lacks(quiet.out, "freed:")

  -- --unblock: the freed tasks that still read `blocked` become open, only when asked
  local gate = new("lib.nvim", "Gate", {})
  local held = new("lib.nvim", "Held", {})
  assert(mutate.set(held, { status = "blocked", blocked_by = "[" .. gate .. "]" }, o))
  local plain_done = run({ "done", gate, "--no-next" })
  eq(plain_done.code, 0, plain_done.err)
  eq(
    require("tasks_nvim.scan").find(held, { root = root }).status,
    "blocked",
    "never changed unasked"
  )
  local gate2 = new("lib.nvim", "Gate two", {})
  local held2 = new("lib.nvim", "Held two", {})
  assert(mutate.set(held2, { status = "blocked", blocked_by = "[" .. gate2 .. "]" }, o))
  local unblock = run({ "done", gate2, "--unblock" })
  eq(unblock.code, 0, unblock.err)
  has(unblock.out, "unblocked\t" .. held2)
  eq(require("tasks_nvim.scan").find(held2, { root = root }).status, "open")
  run({ "done", held, "--no-next" })
  run({ "done", held2, "--no-next" })

  -- the last open tasks: an honest empty answer, never a cheer while work is left
  local pending = lines(run({ "list", "--format=ids" }))
  for _, id in ipairs(pending) do
    if id ~= decide and id ~= top and id ~= cross and id ~= ai then
      run({ "done", id, "--no-next" })
    end
  end
  run({ "done", ai, "--no-next" })
  run({ "done", cross, "--no-next" })
  local waits = run({ "done", top, "--no-next" })
  eq(waits.code, 0, waits.err)
  local left = run({ "next" })
  has(left.out, "next: " .. decide, "the decision is still startable by you")
  run({ "done", decide, "--no-next" })
  local all = run({ "next" })
  has(all.out, "empty: Everything is done.")
end
