---@module 'tasks_nvim.index'
---@brief Render, write and verify the generated task overviews.
---@description
--- `<area>/ROADMAP/TASKS.md` is derived, never hand-written (concept section
--- 4.1): a `GENERATED` comment, a heading with the count, and a GFM table of
--- the open tasks sorted by status rank, prio, slug. The same tasks always
--- render to the same bytes, which is what makes `check` mode possible and
--- keeps the git diff quiet.
---
--- Key responsibilities:
---  - `render`: pure text for one area; nil when it has no open task
---  - `write_area` / `write_all`: write only when the bytes differ, remove a
---    stale file when the last open task is gone, or (`check = true`) only
---    report what would change
---  - `render_global`: the all-areas overview as text, for on-demand export;
---    nothing here ever writes `ALL/TASKS.md` (decision E2: it is not committed)
---
--- Not its job: finding tasks (`scan`) or any UI around the result.

local fsio = require("tasks_nvim.fsio")
local model = require("tasks_nvim.model")
local scan = require("tasks_nvim.scan")
local vault = require("tasks_nvim.vault")

local M = {}

local EN_DASH = "–"
local ELLIPSIS = "…"

---The marker line the first line of every generated index starts with.
M.GENERATED_MARK =
  "<!-- GENERATED by tasks.nvim (:Tasks index) — do not edit; edit tasks/*.md -->"

M.GLOBAL_MARK =
  "<!-- GENERATED on demand (:Tasks list all --to=file:...) — never committed, do not edit; edit tasks/*.md -->"

---Whether `text` is a generated index: its first line is a `<!-- GENERATED` comment. The older marker
---(`... :MyPlugins tasks index ...`) counts too, so an index written by an earlier version is replaced, not
---refused. A file without the marker is somebody's own `TASKS.md` and is never overwritten or removed.
---@param text string
---@return boolean
function M.is_generated(text)
  return fsio.lf(text):sub(1, 15) == "<!-- GENERATED "
end

---Longest summary shown in a table cell, in characters.
M.MAX_SUMMARY = 160

---@param s string
---@return string
local function cell(s)
  return fsio.md_cell(s)
end

---The text of a link `[text](target)`. Brackets are escaped so a title cannot
---open or close a link. A backslash in front of a bracket would swallow that
---escape (`\\[` is an escaped backslash and a live bracket), and one at the end
---would escape the closing `]` the caller adds; such runs are doubled, so the
---number of backslashes in front of every bracket stays odd and the text reads
---back as written.
---@param s string
---@return string
local function link_text(s)
  local text = fsio.double_runs(cell(s), "^[%[%]]", true)
  return (text:gsub("[%[%]]", "\\%0"))
end

---Percent-encode what would end a Markdown link target early or break the
---table row. A valid slug (`a-z0-9-`) never needs it; a file with an odd name
---still gets a row that parses.
---@param s string
---@return string
local function link_target(s)
  return (
    s:gsub('[%c%s()<>|\\%[%]`"#%%]', function(c)
      return ("%%%02X"):format(c:byte())
    end)
  )
end

---The link target of a task below `tasks/`: `<slug>.md`, or `<slug>/<slug>.md`
---for a folder task.
---@param task Tasks.Task
---@return string
local function task_link(task)
  local target = link_target(task.slug)
  return task.folder and (target .. "/" .. target .. ".md") or (target .. ".md")
end

---@param s string
---@param max integer
---@return string
local function truncate(s, max)
  if vim.fn.strchars(s) <= max then
    return s
  end
  return vim.fn.strcharpart(s, 0, max - 1) .. ELLIPSIS
end

---@param task Tasks.Task
---@param max integer
---@return string
local function summary_cell(task, max)
  local text = truncate(task.summary, max)
  if #task.blocked_by > 0 then
    local ids = {}
    for _, id in ipairs(task.blocked_by) do
      ids[#ids + 1] = "`" .. id .. "`"
    end
    local note = "(blockiert durch " .. table.concat(ids, ", ") .. ")"
    text = text == "" and note or (text .. " " .. note)
  end
  return text == "" and EN_DASH or cell(text)
end

---The tasks that appear in an index: in `ROADMAP/tasks/` with an open status.
---@param tasks Tasks.Task[]
---@return Tasks.Task[]
local function open_tasks(tasks)
  local out = {}
  for _, t in ipairs(tasks) do
    if t.location == "roadmap" and model.is_open_status(t.status) then
      out[#out + 1] = t
    end
  end
  return out
end

---Render one area's `ROADMAP/TASKS.md`.
---
---@param area string
---@param tasks Tasks.Task[]  the area's tasks (any status; only open ones are listed)
---@param opts? { max_summary?: integer }
---@return string|nil text  nil when the area has no open task (no file then)
---@return integer open     number of listed tasks
function M.render(area, tasks, opts)
  local max = (opts and opts.max_summary) or M.MAX_SUMMARY
  local open = model.sort(open_tasks(tasks))
  if #open == 0 then
    return nil, 0
  end
  local lines = {
    M.GENERATED_MARK,
    ("# %s — offene Tasks (%d)"):format(area, #open),
    "",
    "| Status | Prio | Effort | Task | Zusammenfassung |",
    "|---|---|---|---|---|",
  }
  for _, t in ipairs(open) do
    lines[#lines + 1] = ("| %s | %s | %s | [%s](tasks/%s) | %s |"):format(
      t.status,
      t.prio and tostring(t.prio) or EN_DASH,
      t.effort and cell(t.effort) or EN_DASH,
      link_text(t.title),
      task_link(t),
      summary_cell(t, max)
    )
  end
  return table.concat(lines, "\n") .. "\n", #open
end

---@class Tasks.IndexOpts : Tasks.ScanOpts
---@field check? boolean        # Report only, write and remove nothing.
---@field max_summary? integer

---Bring one area's index in line with its task files.
---
---`action` is `written`, `removed`, `unchanged`, or (check mode) `stale` with a
---`reason`: `missing` (no file, but open tasks), `outdated` (content differs),
---`orphan` (a file although no task is open). A directory that could not be
---walked is an error: a partial listing would write a wrong index.
---@param area string
---@param opts? Tasks.IndexOpts
---@return Tasks.IndexResult|nil result
---@return string|nil err
function M.write_area(area, opts)
  opts = opts or {}
  local root, rerr = vault.root(opts)
  if not root then
    return nil, rerr
  end
  if not vault.has_area(root, area) then
    return nil, "unknown area: " .. tostring(area)
  end
  local tasks, errors = scan.area(area, vim.tbl_extend("force", opts, { root = root }))
  if not tasks then
    return nil, tostring(errors)
  end
  if type(errors) == "table" and #errors > 0 then
    return nil, "cannot list " .. area .. ": " .. errors[1]
  end

  local path = vault.index_path(root, area)
  local text, open = M.render(area, tasks, opts)
  ---@type Tasks.IndexResult
  local result = { area = area, path = path, open = open, action = "unchanged" }
  local current = fsio.is_file(path) and fsio.read(path) or nil
  if current ~= nil and not M.is_generated(current) then
    return nil,
      ("%s is not a generated index (no GENERATED marker): move or delete it, tasks.nvim will not overwrite it"):format(
        path
      )
  end

  if not text then
    if current ~= nil then
      if opts.check then
        result.action, result.reason = "stale", "orphan"
        return result
      end
      local ok, err = fsio.remove(path)
      if not ok then
        return nil, "cannot remove " .. path .. ": " .. tostring(err)
      end
      result.action = "removed"
    end
    return result
  end

  if current ~= nil and fsio.lf(current) == text then
    return result
  end
  if opts.check then
    result.action = "stale"
    result.reason = current == nil and "missing" or "outdated"
    return result
  end
  -- A checkout that uses CRLF keeps it: only the content changed, not the style.
  if current ~= nil and fsio.eol_of(current) == "\r\n" then
    text = text:gsub("\n", "\r\n")
  end
  local ok, err = fsio.write_atomic(path, text)
  if not ok then
    return nil, "cannot write " .. path .. ": " .. tostring(err)
  end
  result.action = "written"
  return result
end

---@class Tasks.WriteAllOpts : Tasks.IndexOpts
---@field areas? string[]   # Only these areas (default: every area of the vault).

---`write_area` for every area (or only `opts.areas`). Best effort: one failing
---area does not stop the others (ERR-42); each failure is listed in `errors`.
---@param opts? Tasks.WriteAllOpts
---@return Tasks.IndexResult[]|nil results
---@return string[] errors
function M.write_all(opts)
  opts = opts or {}
  local root, rerr = vault.root(opts)
  if not root then
    return nil, { rerr }
  end
  local names = opts.areas
  if not names then
    names = {}
    for _, a in ipairs(vault.areas(root)) do
      names[#names + 1] = a.name
    end
  end
  local results, errors = {}, {}
  for _, name in ipairs(names) do
    local res, err = M.write_area(name, vim.tbl_extend("force", opts, { root = root }))
    if res then
      results[#results + 1] = res
    else
      errors[#errors + 1] = name .. ": " .. tostring(err)
    end
  end
  return results, errors
end

---@param tasks Tasks.Task[]
---@return string|nil oldest  earliest `updated` (else `created`) among the tasks
local function oldest_date(tasks)
  local oldest
  for _, t in ipairs(tasks) do
    local d = t.updated or t.created
    if d and model.is_date(d) and (oldest == nil or d < oldest) then
      oldest = d
    end
  end
  return oldest
end

---@class Tasks.GlobalOpts
---@field top? integer              # Rows in the cross-area list (default 20).
---@field areas? string[]           # Areas to list even when they have no open task.
---@field links? boolean            # Link to the area index / task files (default true).
---@field link_prefix? string       # Prefix of those links (default `../`, i.e. the file sits in `ALL/`).
---@field max_summary? integer

---Render the all-areas overview (concept section 4.2): one row per area with
---the count per status, the highest prio and the oldest update, then the top
---tasks across all areas. Returns text only -- the caller decides where it
---goes, and nothing here writes `ALL/TASKS.md`.
---@param tasks Tasks.Task[]
---@param opts? Tasks.GlobalOpts
---@return string text
---@return integer open  number of open tasks counted
function M.render_global(tasks, opts)
  opts = opts or {}
  local top = opts.top or 20
  local max = opts.max_summary or M.MAX_SUMMARY
  local links = opts.links ~= false
  local prefix = opts.link_prefix or "../"
  local open = model.sort(open_tasks(tasks))

  local by_area, order = {}, {}
  local function bucket(name)
    if not by_area[name] then
      by_area[name] = {}
      order[#order + 1] = name
    end
    return by_area[name]
  end
  for _, name in ipairs(opts.areas or {}) do
    bucket(name)
  end
  for _, t in ipairs(open) do
    local list = bucket(t.area)
    list[#list + 1] = t
  end
  table.sort(order)

  local with_tasks = 0
  for _, name in ipairs(order) do
    if #by_area[name] > 0 then
      with_tasks = with_tasks + 1
    end
  end

  local lines = {
    M.GLOBAL_MARK,
    ("# Offene Tasks — alle Bereiche (%d in %d Bereichen)"):format(#open, with_tasks),
    "",
    "## Pro Bereich",
    "",
    "| Bereich | doing | decision | blocked | open | parked | Gesamt | Prio | Ältester Stand |",
    "|---|---|---|---|---|---|---|---|---|",
  }
  for _, name in ipairs(order) do
    local list = by_area[name]
    local counts = {}
    local best
    for _, t in ipairs(list) do
      counts[t.status] = (counts[t.status] or 0) + 1
      if t.prio and (best == nil or t.prio < best) then
        best = t.prio
      end
    end
    local label = name
    if links then
      label = ("[%s](%s%s/ROADMAP/TASKS.md)"):format(name, prefix, link_target(name))
    end
    lines[#lines + 1] = ("| %s | %d | %d | %d | %d | %d | %d | %s | %s |"):format(
      label,
      counts.doing or 0,
      counts.decision or 0,
      counts.blocked or 0,
      counts.open or 0,
      counts.parked or 0,
      #list,
      best and tostring(best) or EN_DASH,
      oldest_date(list) or EN_DASH
    )
  end

  local shown = math.min(top, #open)
  lines[#lines + 1] = ""
  lines[#lines + 1] = ("## Top %d"):format(shown)
  lines[#lines + 1] = ""
  lines[#lines + 1] = "| Status | Prio | Effort | Bereich | Task | Zusammenfassung |"
  lines[#lines + 1] = "|---|---|---|---|---|---|"
  for i = 1, shown do
    local t = open[i]
    local title = link_text(t.title)
    if links then
      title = ("[%s](%s%s/ROADMAP/tasks/%s)"):format(
        title,
        prefix,
        link_target(t.area),
        task_link(t)
      )
    end
    lines[#lines + 1] = ("| %s | %s | %s | %s | %s | %s |"):format(
      t.status,
      t.prio and tostring(t.prio) or EN_DASH,
      t.effort and cell(t.effort) or EN_DASH,
      cell(t.area),
      title,
      summary_cell(t, max)
    )
  end
  return table.concat(lines, "\n") .. "\n", #open
end

return M
