---@module 'tasks_nvim.plan_view'
---@brief A `Tasks.Plan` as Markdown, tab-separated lines or ids -- pure text, nothing is written or shown here.
---@description
--- `markdown` is for reading (and for `--to=buffer|file|clipboard|mdview`), `tsv` and `ids` are for scripts. Every
--- cell that comes from a task file goes through `fsio.md_cell` / `fsio.clean`: a title is data, not markup and not a
--- terminal command.
---
--- The estimate line is `estimate.describe` and always carries its caveat ("estimate from the scale, not a
--- promise"); the critical path says how many of its tasks have no effort and were counted as one day.
---
--- Not its job: computing the plan (`plan`), the sums (`estimate`), writing the text anywhere (`ui.view`).

local estimate = require("tasks_nvim.estimate")
local fsio = require("tasks_nvim.fsio")
local model = require("tasks_nvim.model")

local M = {}

---@class Tasks.PlanViewOpts
---@field title? string        # Names the scope ("lib.nvim", "for lib.nvim/x", ...).
---@field today? string
---@field done? Tasks.Task[]   # Finished tasks of the same scope (for the progress figure).
---@field ready_only? boolean  # Only the "ready now" part.

---@param plan Tasks.Plan
---@return Tasks.Task[]
local function tasks_of(plan)
  local out = {}
  for _, id in ipairs(plan.ids) do
    out[#out + 1] = plan.nodes[id].task
  end
  return out
end

---What a row says about a task besides its columns.
---@param node Tasks.PlanNode
---@return string
local function hint(node)
  local parts = {}
  if node.in_cycle then
    parts[#parts + 1] = "in a cycle"
  elseif node.behind_cycle then
    parts[#parts + 1] = "behind a cycle"
  end
  if node.inversion then
    parts[#parts + 1] = ("prio %s -> %d because of %s"):format(
      node.inversion.from and tostring(node.inversion.from) or "-",
      node.inversion.to,
      node.inversion.because
    )
  end
  if #node.external > 0 then
    parts[#parts + 1] = "external: " .. table.concat(node.external, ", ")
  end
  if node.state == "stuck" and not node.in_cycle and not node.behind_cycle then
    parts[#parts + 1] = "stuck"
  elseif node.state == "freed" then
    parts[#parts + 1] = "status says blocked, nothing blocks it"
  end
  return table.concat(parts, "; ")
end

---@param node Tasks.PlanNode
---@return string
local function prio_text(node)
  local t = node.task
  return t.prio and ("P%d"):format(t.prio) or "-"
end

---@param node Tasks.PlanNode
---@return string
local function waits_text(node)
  if #node.open_blockers == 0 then
    return ""
  end
  return "waits on " .. table.concat(node.open_blockers, ", ")
end

---A row of a Markdown table.
---@param cells string[]
---@return string
local function row(cells)
  local out = {}
  for _, c in ipairs(cells) do
    out[#out + 1] = fsio.md_cell(c)
  end
  return "| " .. table.concat(out, " | ") .. " |"
end

---The plan as Markdown.
---@param plan Tasks.Plan
---@param opts? Tasks.PlanViewOpts
---@return string
function M.markdown(plan, opts)
  opts = opts or {}
  local tasks = tasks_of(plan)
  local sums = estimate.rollup(tasks, { done = opts.done })
  local lines = {
    "<!-- GENERATED by `tasks plan` -- do not edit -->",
    "# Plan"
      .. (opts.title and (": " .. fsio.clean(opts.title)) or "")
      .. (opts.today and (" -- " .. opts.today) or ""),
    "",
    ("%d task%s \194\183 %d ready now \194\183 %d waiting for a decision"):format(
      #tasks,
      #tasks == 1 and "" or "s",
      #plan.ready,
      #plan.decisions
    ),
    "",
    estimate.describe(sums),
    "",
  }
  if plan.critical.days > 0 then
    local text = ("Critical path: %s d over %d task%s"):format(
      estimate.fmt_days(plan.critical.days),
      #plan.critical.path,
      #plan.critical.path == 1 and "" or "s"
    )
    if plan.critical.unknown > 0 then
      text = text .. (" (%d without effort counted as 1 day)"):format(plan.critical.unknown)
    end
    lines[#lines + 1] = text
    lines[#lines + 1] = ""
  end

  -- Ready now
  lines[#lines + 1] = "## Ready now"
  lines[#lines + 1] = ""
  local shown_ready = 0
  local ready_rows = {}
  for _, id in ipairs(plan.ready) do
    local node = plan.nodes[id]
    if node.state == "ready" then
      ready_rows[#ready_rows + 1] = row({
        prio_text(node),
        tostring(node.leverage),
        node.task.effort or "-",
        id,
        fsio.clean(node.task.title),
        hint(node),
      })
      shown_ready = shown_ready + 1
    end
  end
  if shown_ready == 0 then
    lines[#lines + 1] = "_Nothing can be started right now._"
  else
    lines[#lines + 1] = "| Prio | Leverage | Effort | Task | Title | Note |"
    lines[#lines + 1] = "| --- | --- | --- | --- | --- | --- |"
    vim.list_extend(lines, ready_rows)
  end
  lines[#lines + 1] = ""
  if opts.ready_only then
    return table.concat(lines, "\n") .. "\n"
  end

  -- Decisions by leverage
  if #plan.decisions > 0 then
    lines[#lines + 1] = "## Decisions by leverage"
    lines[#lines + 1] = ""
    lines[#lines + 1] = "| Leverage | Decision | Unlocks |"
    lines[#lines + 1] = "| --- | --- | --- |"
    for _, id in ipairs(plan.decisions) do
      local node = plan.nodes[id]
      local unlocks = {}
      for _, other in ipairs(plan.ids) do
        for _, b in ipairs(plan.nodes[other].task.blocked_by or {}) do
          if b == id then
            unlocks[#unlocks + 1] = other
          end
        end
      end
      lines[#lines + 1] = row({
        tostring(node.leverage),
        id .. " -- " .. fsio.clean(node.task.title),
        table.concat(unlocks, ", "),
      })
    end
    lines[#lines + 1] = ""
  end

  -- Stages
  for i, stage in ipairs(plan.stages) do
    lines[#lines + 1] = ("## Stage %d"):format(i - 1)
    lines[#lines + 1] = ""
    lines[#lines + 1] = "| Task | Status | Effort | Waits on | Note |"
    lines[#lines + 1] = "| --- | --- | --- | --- | --- |"
    for _, id in ipairs(stage) do
      local node = plan.nodes[id]
      lines[#lines + 1] = row({
        id .. " -- " .. fsio.clean(node.task.title),
        node.task.status or "?",
        node.task.effort or "-",
        waits_text(node),
        hint(node),
      })
    end
    lines[#lines + 1] = ""
  end

  if #plan.critical.path > 0 then
    lines[#lines + 1] = "## Critical path"
    lines[#lines + 1] = ""
    for i, id in ipairs(plan.critical.path) do
      local t = plan.nodes[id].task
      lines[#lines + 1] = ("%d. %s (%s)"):format(i, fsio.clean(id), t.effort or "no effort")
    end
    lines[#lines + 1] = ""
  end

  if #plan.warnings > 0 then
    lines[#lines + 1] = "## Warnings"
    lines[#lines + 1] = ""
    for _, w in ipairs(plan.warnings) do
      lines[#lines + 1] = ("- `%s` %s"):format(w.code, fsio.clean(w.msg))
    end
    lines[#lines + 1] = ""
  end
  return table.concat(lines, "\n") .. "\n"
end

---One line per task in plan order: `stage id state status prio effort leverage title`, tab-separated.
---@param plan Tasks.Plan
---@param opts? { ready_only?: boolean }
---@return string[] lines
function M.tsv(plan, opts)
  opts = opts or {}
  local ids = opts.ready_only and plan.ready or plan.ids
  local out = {}
  for _, id in ipairs(ids) do
    local node = plan.nodes[id]
    local t = node.task
    out[#out + 1] = table.concat({
      node.stage and tostring(node.stage) or "-",
      fsio.clean(id),
      node.state,
      t.status or "?",
      t.prio and tostring(t.prio) or "-",
      t.effort or "-",
      tostring(node.leverage),
      fsio.clean(t.title),
    }, "\t")
  end
  return out
end

---The ids in plan order (or only the ready ones).
---@param plan Tasks.Plan
---@param opts? { ready_only?: boolean }
---@return string[]
function M.ids(plan, opts)
  opts = opts or {}
  return vim.deepcopy(opts.ready_only and plan.ready or plan.ids)
end

---The best ready tasks as lines for `next`: `id <tab> title`, the reason first for the top one.
---@param pick Tasks.NextPick
---@return string[] lines
function M.next_lines(pick)
  local out = {}
  if pick.task then
    out[#out + 1] = ("next: %s\t%s\t%s"):format(
      pick.task.id,
      fsio.clean(pick.task.title),
      pick.reason or ""
    )
    for _, t in ipairs(pick.alternatives) do
      out[#out + 1] = ("then: %s\t%s"):format(t.id, fsio.clean(t.title))
    end
  end
  if #pick.freed > 0 then
    out[#out + 1] = "freed: " .. table.concat(pick.freed, ", ")
  end
  for _, t in ipairs(pick.cdx) do
    out[#out + 1] = ("cdx: %s\t%s"):format(t.id, fsio.clean(t.title))
  end
  if pick.empty then
    out[#out + 1] = "empty: " .. M.empty_text(pick.empty)
  end
  return out
end

---The honest sentence for an empty answer.
---@param empty Tasks.NextEmpty
---@return string
function M.empty_text(empty)
  if empty.kind == "all_done" then
    return "Everything is done."
  end
  if empty.kind == "only_cdx" then
    return "Nothing for you; what can be started is for an AI session."
  end
  local waiting = {}
  if empty.for_me > 0 then
    waiting[#waiting + 1] = ("%d for you"):format(empty.for_me)
  end
  if empty.waiting > 0 then
    waiting[#waiting + 1] = ("%d blocked"):format(empty.waiting)
  end
  if empty.blocked_status > 0 then
    waiting[#waiting + 1] = ("%d marked blocked with nothing blocking"):format(empty.blocked_status)
  end
  if empty.parked > 0 then
    waiting[#waiting + 1] = ("%d parked"):format(empty.parked)
  end
  return "Nothing can be started. Still open: "
    .. (#waiting > 0 and table.concat(waiting, ", ") or "see the list")
    .. "."
end

---A short plain-language description of the next-task answer (a popup, a message).
---@param pick Tasks.NextPick
---@param done_id? string
---@return string[] lines
function M.next_message(pick, done_id)
  local lines = {}
  if done_id then
    local head = "Done: " .. fsio.clean(done_id)
    if #pick.freed > 0 then
      head = head .. " \194\183 freed: " .. fsio.clean(table.concat(pick.freed, ", "))
    end
    lines[#lines + 1] = head
  end
  if pick.task then
    local t = pick.task
    local facts = {}
    if t.prio then
      facts[#facts + 1] = "P" .. t.prio
    end
    if t.effort then
      facts[#facts + 1] = t.effort
    end
    if t.value then
      facts[#facts + 1] = "value " .. t.value
    end
    local roi = model.roi(t)
    if roi then
      facts[#facts + 1] = ("roi %.1f"):format(roi)
    end
    lines[#lines + 1] = ("Next: %s -- %s%s"):format(
      fsio.clean(t.id),
      fsio.clean(t.title),
      #facts > 0 and (" (" .. table.concat(facts, " \194\183 ") .. ")") or ""
    )
    local why = {
      freed = "freed by the task you just finished",
      area = "same area",
      vault = "elsewhere in the vault",
    }
    lines[#lines + 1] = "Why: " .. (why[pick.reason or ""] or "best ready task")
  else
    local empty = pick.empty
    lines[#lines + 1] = empty and M.empty_text(empty) or "Nothing to start."
    if empty and empty.area_empty then
      lines[#lines + 1] = "No open task left in that area."
    end
  end
  if #pick.cdx > 0 then
    local names = {}
    for _, t in ipairs(pick.cdx) do
      names[#names + 1] = t.id
    end
    lines[#lines + 1] = "An AI session could take: " .. fsio.clean(table.concat(names, ", "))
  end
  return lines
end

return M
