---@module 'tasks_nvim.plan_view'
---@brief A `Tasks.Plan` as Markdown, tab-separated lines or ids -- pure text, nothing is written or shown here.
---@description
--- `markdown` is for reading (and for `--to=buffer|file|clipboard|mdview`), `tsv` and `ids` are for scripts. Every
--- cell that comes from a task file goes through `fsio.md_cell` / `fsio.clean`: a title is data, not markup and not a
--- terminal command.
---
--- The estimate line is `estimate.describe` and always carries its caveat ("estimate from the scale, not a
--- promise"); the critical path says how many of its tasks have no effort and were counted as one day.
---
--- Not its job: computing the plan (`plan`), the sums (`estimate`), writing the text anywhere (`ui.view`).

local estimate = require("tasks_nvim.estimate")
local fsio = require("tasks_nvim.fsio")
local model = require("tasks_nvim.model")

local M = {}

---@class Tasks.PlanViewOpts
---@field title? string        # Names the scope ("lib.nvim", "for lib.nvim/x", ...).
---@field today? string
---@field done? Tasks.Task[]   # Finished tasks of the same scope (for the progress figure).
---@field ready_only? boolean  # Only the "ready now" part.
---@field with_steps? boolean  # Under each stage: the `## Plan` steps of its tasks and their progress.
---@field block? boolean       # For a marker block in another document: no generated-comment, headings one level deeper.
---@field plan_file? Tasks.PlanFile  # The plan file of a `--plan=` scope: its goal and status head the text.

---@param plan Tasks.Plan
---@return Tasks.Task[]
local function tasks_of(plan)
  local out = {}
  for _, id in ipairs(plan.ids) do
    out[#out + 1] = plan.nodes[id].task
  end
  return out
end

---What a row says about a task besides its columns.
---@param node Tasks.PlanNode
---@return string
local function hint(node)
  local parts = {}
  if node.in_cycle then
    parts[#parts + 1] = "in a cycle"
  elseif node.behind_cycle then
    parts[#parts + 1] = "behind a cycle"
  end
  if node.inversion then
    parts[#parts + 1] = ("prio %s -> %d because of %s"):format(
      node.inversion.from and tostring(node.inversion.from) or "-",
      node.inversion.to,
      node.inversion.because
    )
  end
  if #node.external > 0 then
    parts[#parts + 1] = "external: " .. table.concat(node.external, ", ")
  end
  if #node.same_file > 0 then
    parts[#parts + 1] = "same-file with " .. table.concat(node.same_file, ", ")
  end
  if node.state == "stuck" and not node.in_cycle and not node.behind_cycle then
    parts[#parts + 1] = "stuck"
  elseif node.state == "freed" then
    parts[#parts + 1] = "status says blocked, nothing blocks it"
  end
  return table.concat(parts, "; ")
end

---@param node Tasks.PlanNode
---@return string
local function prio_text(node)
  local t = node.task
  return t.prio and ("P%d"):format(t.prio) or "-"
end

---@param node Tasks.PlanNode
---@return string
local function waits_text(node)
  if #node.open_blockers == 0 then
    return ""
  end
  return "waits on " .. table.concat(node.open_blockers, ", ")
end

---A row of a Markdown table.
---@param cells string[]
---@return string
local function row(cells)
  local out = {}
  for _, c in ipairs(cells) do
    out[#out + 1] = fsio.md_cell(c)
  end
  return "| " .. table.concat(out, " | ") .. " |"
end

---The plan as Markdown.
---@param plan Tasks.Plan
---@param opts? Tasks.PlanViewOpts
---@return string
function M.markdown(plan, opts)
  opts = opts or {}
  local tasks = tasks_of(plan)
  local sums = estimate.rollup(tasks, { done = opts.done })
  local lines = {
    "<!-- GENERATED by `tasks plan` -- do not edit -->",
    "# Plan"
      .. (opts.title and (": " .. fsio.clean(opts.title)) or "")
      .. (opts.today and (" -- " .. opts.today) or ""),
    "",
  }
  local file = opts.plan_file
  if file then
    lines[#lines + 1] = ("**%s** (%s)"):format(fsio.clean(file.title), file.status or "?")
    if file.summary ~= "" and file.summary ~= file.title then
      lines[#lines + 1] = ""
      -- a quote, never a bare line: the summary is the plan's own text, and a line of it that reads like a marker
      -- (`<!-- GENERATED:plan end -->`) or a heading would split the generated block it sits in
      lines[#lines + 1] = "> " .. fsio.clean(file.summary)
    end
    if #file.phase_order > 0 then
      lines[#lines + 1] = ""
      lines[#lines + 1] = ("Stages: %s%s"):format(
        table.concat(file.phase_order, " > "),
        file.gate == "hard" and " (a stage may not begin before the earlier ones are finished)"
          or ""
      )
    end
    if file.target then
      lines[#lines + 1] = ""
      lines[#lines + 1] = "Done when: " .. fsio.clean(file.target)
    end
    lines[#lines + 1] = ""
  end
  vim.list_extend(lines, {
    ("%d task%s \194\183 %d ready now \194\183 %d waiting for a decision"):format(
      #tasks,
      #tasks == 1 and "" or "s",
      #plan.ready,
      #plan.decisions
    ),
    "",
    estimate.describe(sums),
    "",
  })
  if plan.critical.days > 0 then
    local text = ("Critical path: %s d over %d task%s"):format(
      estimate.fmt_days(plan.critical.days),
      #plan.critical.path,
      #plan.critical.path == 1 and "" or "s"
    )
    if plan.critical.unknown > 0 then
      text = text .. (" (%d without effort counted as 1 day)"):format(plan.critical.unknown)
    end
    lines[#lines + 1] = text
    lines[#lines + 1] = ""
  end

  -- Ready now
  lines[#lines + 1] = "## Ready now"
  lines[#lines + 1] = ""
  local shown_ready = 0
  local ready_rows = {}
  for _, id in ipairs(plan.ready) do
    local node = plan.nodes[id]
    if node.state == "ready" then
      ready_rows[#ready_rows + 1] = row({
        prio_text(node),
        tostring(node.leverage),
        node.task.effort or "-",
        id,
        fsio.clean(node.task.title),
        hint(node),
      })
      shown_ready = shown_ready + 1
    end
  end
  if shown_ready == 0 then
    lines[#lines + 1] = "_Nothing can be started right now._"
  else
    lines[#lines + 1] = "| Prio | Leverage | Effort | Task | Title | Note |"
    lines[#lines + 1] = "| --- | --- | --- | --- | --- | --- |"
    vim.list_extend(lines, ready_rows)
  end
  lines[#lines + 1] = ""
  if opts.ready_only then
    return M.finish(lines, opts)
  end

  -- Decisions by leverage
  if #plan.decisions > 0 then
    lines[#lines + 1] = "## Decisions by leverage"
    lines[#lines + 1] = ""
    lines[#lines + 1] = "| Leverage | Decision | Unlocks |"
    lines[#lines + 1] = "| --- | --- | --- |"
    for _, id in ipairs(plan.decisions) do
      local node = plan.nodes[id]
      local unlocks = {}
      for _, other in ipairs(plan.ids) do
        for _, b in ipairs(plan.nodes[other].task.blocked_by or {}) do
          if b == id then
            unlocks[#unlocks + 1] = other
          end
        end
      end
      lines[#lines + 1] = row({
        tostring(node.leverage),
        id .. " -- " .. fsio.clean(node.task.title),
        table.concat(unlocks, ", "),
      })
    end
    lines[#lines + 1] = ""
  end

  -- Stages
  for i, stage in ipairs(plan.stages) do
    lines[#lines + 1] = ("## Stage %d"):format(i - 1)
    lines[#lines + 1] = ""
    for _, conflict in ipairs(plan.conflicts) do
      if conflict.stage == i - 1 then
        lines[#lines + 1] = ("_Not parallel: `%s` is named by %s -- the order below says which first._"):format(
          fsio.clean(conflict.file),
          fsio.clean(table.concat(conflict.ids, ", "))
        )
        lines[#lines + 1] = ""
      end
    end
    lines[#lines + 1] = "| Task | Status | Effort | Waits on | Note |"
    lines[#lines + 1] = "| --- | --- | --- | --- | --- |"
    for _, id in ipairs(stage) do
      local node = plan.nodes[id]
      lines[#lines + 1] = row({
        id .. " -- " .. fsio.clean(node.task.title),
        node.task.status or "?",
        node.task.effort or "-",
        waits_text(node),
        hint(node),
      })
    end
    lines[#lines + 1] = ""
    if opts.with_steps then
      for _, id in ipairs(stage) do
        local steps = plan.nodes[id].task.plan_steps
        if steps then
          lines[#lines + 1] = ("**%s** -- %d/%d steps"):format(
            fsio.clean(id),
            steps.ticked,
            steps.total
          )
          lines[#lines + 1] = ""
          for _, item in ipairs(steps.items) do
            lines[#lines + 1] = ("- [%s] %s"):format(
              item.done and "x" or " ",
              fsio.clean(item.text)
            )
          end
          lines[#lines + 1] = ""
        end
      end
    end
  end

  if #plan.critical.path > 0 then
    lines[#lines + 1] = "## Critical path"
    lines[#lines + 1] = ""
    for i, id in ipairs(plan.critical.path) do
      local t = plan.nodes[id].task
      lines[#lines + 1] = ("%d. %s (%s)"):format(i, fsio.clean(id), t.effort or "no effort")
    end
    lines[#lines + 1] = ""
  end

  if #plan.warnings > 0 then
    lines[#lines + 1] = "## Warnings"
    lines[#lines + 1] = ""
    for _, w in ipairs(plan.warnings) do
      lines[#lines + 1] = ("- `%s` %s"):format(w.code, fsio.clean(w.msg))
    end
    lines[#lines + 1] = ""
  end
  return M.finish(lines, opts)
end

---The finished text: for a marker block (`opts.block`) the generated-comment goes and the headings move one level
---down (the document around it has its own `#`), code fences are left alone.
---@param lines string[]
---@param opts Tasks.PlanViewOpts
---@return string
function M.finish(lines, opts)
  if opts.block then
    local out, fenced = {}, false
    for i, line in ipairs(lines) do
      if line:match("^```") then
        fenced = not fenced
      end
      if i == 1 and line:find("GENERATED by", 1, true) then
        -- dropped: the markers around the block say it is generated
      elseif not fenced and line:match("^#+%s") then
        out[#out + 1] = "#" .. line
      else
        out[#out + 1] = line
      end
    end
    lines = out
    while lines[#lines] == "" do
      lines[#lines] = nil
    end
  end
  return table.concat(lines, "\n") .. "\n"
end

---The default name of a marker block for a scope: the plan's slug, the area, `for-<slug>` or `all`.
---@param opts { area?: string, for_id?: string, plan_id?: string }
---@return string
function M.default_scope(opts)
  if opts.plan_id then
    return (opts.plan_id:match("([^/]+)$")) or opts.plan_id
  elseif opts.for_id then
    return "for-" .. ((opts.for_id:match("([^/]+)$")) or opts.for_id)
  end
  return opts.area or "all"
end

local START_PREFIX = "<!-- GENERATED:plan scope="
local START_SUFFIX = " start -->"
local END_LINE = "<!-- GENERATED:plan end -->"

---The marker lines of a block for `scope`.
---@param scope string
---@param attrs? table<string, string>
---@return string start
---@return string finish
function M.block_markers(scope, attrs)
  return M.start_line(scope, attrs), END_LINE
end

---The start marker line of a block: `<!-- GENERATED:plan scope=<name> [key=value ...] start -->`. The attributes
---record how the block was made (the target, the view, the filters), so a later refresh builds the same block.
---@param scope string
---@param attrs? table<string, string>
---@return string
function M.start_line(scope, attrs)
  local keys = {}
  for key in pairs(attrs or {}) do
    keys[#keys + 1] = key
  end
  table.sort(keys)
  local parts = { START_PREFIX .. scope }
  for _, key in ipairs(keys) do
    parts[#parts + 1] = key .. "=" .. (attrs or {})[key]
  end
  return table.concat(parts, " ") .. START_SUFFIX
end

---Read a start marker line: its scope name and attributes. Linear: no pattern runs over the user's text. A line that
---is no start marker answers `nil`; a trailing CR (a CRLF document) is no part of it.
---@param line string
---@return string|nil scope
---@return table<string, string>|nil attrs
function M.parse_start(line)
  if line:sub(1, #START_PREFIX) ~= START_PREFIX then
    return nil, nil
  end
  local trimmed = fsio.trim(line)
  if
    #trimmed < #START_PREFIX + #START_SUFFIX + 1 or trimmed:sub(-#START_SUFFIX) ~= START_SUFFIX
  then
    return nil, nil
  end
  local middle = trimmed:sub(#START_PREFIX + 1, #trimmed - #START_SUFFIX)
  local scope, attrs = nil, {}
  for word in middle:gmatch("%S+") do
    if not scope then
      scope = word
    else
      local key, value = word:match("^([%w_%-]+)=(.*)$")
      if key then
        attrs[key] = value
      end
    end
  end
  if not scope then
    return nil, nil
  end
  return scope, attrs
end

---@param line string
---@return boolean
local function is_end(line)
  return line:sub(1, #END_LINE) == END_LINE and fsio.trim(line) == END_LINE
end

---@class Tasks.MarkerBlock
---@field scope string
---@field attrs table<string, string>
---@field start integer       # Line number of the start marker.
---@field finish? integer     # Line number of the end marker; nil when the block is not closed.
---@field err? string         # Why the block cannot be replaced (no end marker before the next start).

---The marker blocks of a document, in order. A marker inside a fenced code block (a doc that SHOWS the syntax) is
---no marker. Lines are split on `\n` only: a trailing `\r` stays with its line.
---@param text string
---@return Tasks.MarkerBlock[] blocks
---@return string[] lines
function M.parse_blocks(text)
  local lines = vim.split(text, "\n", { plain = true })
  local blocks, open = {}, nil
  local fence_char, fence_len
  for i, line in ipairs(lines) do
    local indent, run = line:match("^( *)([`~]+)")
    local is_fence = indent ~= nil
      and #indent <= 3
      and #run >= 3
      and not run:find("[^" .. run:sub(1, 1) .. "]")
    if fence_char then
      -- a closing fence: the same character, at least as long, nothing else on the line
      if
        is_fence
        and run:sub(1, 1) == fence_char
        and #run >= fence_len
        and fsio.trim(line:sub(#indent + #run + 1)) == ""
      then
        fence_char, fence_len = nil, nil
      end
    elseif is_fence then
      fence_char, fence_len = run:sub(1, 1), #run
    else
      local scope, attrs = M.parse_start(line)
      if scope then
        if open then
          open.err = ("the block `%s` is not closed before the next block starts"):format(
            open.scope
          )
        end
        open = { scope = scope, attrs = attrs, start = i }
        blocks[#blocks + 1] = open
      elseif open and is_end(line) then
        open.finish = i
        open = nil
      end
    end
  end
  for _, block in ipairs(blocks) do
    if not block.finish and not block.err then
      block.err = ("the block `%s` has no `%s` line"):format(block.scope, END_LINE)
    end
  end
  return blocks, lines
end

---The names of the marker blocks in a document, each once, in the order they first appear.
---@param text string
---@return string[] scopes
function M.block_scopes(text)
  local out, seen = {}, {}
  for _, block in ipairs((M.parse_blocks(text))) do
    if not seen[block.scope] then
      seen[block.scope] = true
      out[#out + 1] = block.scope
    end
  end
  return out
end

---Rewrite the marker blocks of `text` that `pick` chooses, nothing else: every other line keeps its own bytes and its
---own line ending (a document with mixed endings is not normalised). `pick(block)` answers the new body (Markdown, with
---or without a trailing newline) and, optionally, the attributes the start marker is rewritten with; `nil` leaves the
---block alone. The body takes the line ending of its block's start marker. A chosen block that cannot be replaced (no
---end marker) is an error, and so is a body that contains a marker line (it would split the block on the next read).
---@param text string
---@param pick fun(block: Tasks.MarkerBlock): string|nil, table<string, string>|nil
---@return string|nil new_text
---@return string|nil err
---@return boolean|nil changed
---@return string[]|nil changed_scopes   # The scopes of the blocks whose body is not what it was (each once).
function M.replace_blocks(text, pick)
  local blocks, lines = M.parse_blocks(text)
  local out, at = {}, 1
  local changed_scopes, seen = {}, {}
  for _, block in ipairs(blocks) do
    local body, attrs = pick(block)
    if body ~= nil then
      if block.err then
        return nil, block.err
      end
      local cr = lines[block.start]:sub(-1) == "\r" and "\r" or ""
      while body:sub(-1) == "\n" do
        body = body:sub(1, -2)
      end
      local fresh = vim.split(body, "\n", { plain = true })
      for _, line in ipairs(fresh) do
        if M.parse_start(line) or is_end(line) then
          return nil, "the generated text contains a marker line: " .. line
        end
      end
      vim.list_extend(out, lines, at, block.start - 1)
      local start_line = attrs and (M.start_line(block.scope, attrs) .. cr) or lines[block.start]
      local finish = block.finish --[[@as integer]]
      local was, now = { lines[block.start] }, { start_line }
      for i = block.start + 1, finish - 1 do
        was[#was + 1] = lines[i]
      end
      for _, line in ipairs(fresh) do
        now[#now + 1] = line .. cr
      end
      vim.list_extend(out, now)
      if not seen[block.scope] and table.concat(was, "\n") ~= table.concat(now, "\n") then
        seen[block.scope] = true
        changed_scopes[#changed_scopes + 1] = block.scope
      end
      at = finish
    end
  end
  vim.list_extend(out, lines, at, #lines)
  local result = table.concat(out, "\n")
  return result, nil, result ~= text, changed_scopes
end

---Replace the body of every block named `scope` in `text` (see `replace_blocks`). `attrs` rewrites their start
---markers. `nil, err` when there is no such block (the error lists the scopes that exist) or one is not closed.
---@param text string
---@param scope string
---@param body string
---@param attrs? table<string, string>
---@return string|nil new_text
---@return string|nil err
---@return boolean|nil changed
function M.replace_block(text, scope, body, attrs)
  local found = false
  local result, err, changed = M.replace_blocks(text, function(block)
    if block.scope == scope then
      found = true
      return body, attrs
    end
  end)
  if not result then
    return nil, err
  end
  if not found then
    local have = M.block_scopes(text)
    return nil,
      ("no block `%s` in the file%s"):format(
        M.start_line(scope),
        #have > 0 and (" (it has: " .. table.concat(have, ", ") .. ")") or ""
      )
  end
  return result, nil, changed
end

---One line per task in plan order: `stage id state status prio effort leverage title`, tab-separated.
---@param plan Tasks.Plan
---@param opts? { ready_only?: boolean }
---@return string[] lines
function M.tsv(plan, opts)
  opts = opts or {}
  local ids = opts.ready_only and plan.ready or plan.ids
  local out = {}
  for _, id in ipairs(ids) do
    local node = plan.nodes[id]
    local t = node.task
    out[#out + 1] = table.concat({
      node.stage and tostring(node.stage) or "-",
      fsio.clean(id),
      node.state,
      t.status or "?",
      t.prio and tostring(t.prio) or "-",
      t.effort or "-",
      tostring(node.leverage),
      fsio.clean(t.title),
    }, "\t")
  end
  return out
end

---The ids in plan order (or only the ready ones).
---@param plan Tasks.Plan
---@param opts? { ready_only?: boolean }
---@return string[]
function M.ids(plan, opts)
  opts = opts or {}
  return vim.deepcopy(opts.ready_only and plan.ready or plan.ids)
end

---The best ready tasks as lines for `next`: `id <tab> title`, the reason first for the top one.
---@param pick Tasks.NextPick
---@return string[] lines
function M.next_lines(pick)
  local out = {}
  if pick.task then
    out[#out + 1] = ("next: %s\t%s\t%s"):format(
      pick.task.id,
      fsio.clean(pick.task.title),
      pick.reason or ""
    )
    for _, t in ipairs(pick.alternatives) do
      out[#out + 1] = ("then: %s\t%s"):format(t.id, fsio.clean(t.title))
    end
  end
  if #pick.freed > 0 then
    out[#out + 1] = "freed: " .. table.concat(pick.freed, ", ")
  end
  for _, t in ipairs(pick.cdx) do
    out[#out + 1] = ("cdx: %s\t%s"):format(t.id, fsio.clean(t.title))
  end
  if pick.empty then
    out[#out + 1] = "empty: " .. M.empty_text(pick.empty)
  end
  return out
end

---The honest sentence for an empty answer.
---@param empty Tasks.NextEmpty
---@return string
function M.empty_text(empty)
  if empty.kind == "all_done" then
    return "Everything is done."
  end
  if empty.kind == "only_cdx" then
    return "Nothing for you; what can be started is for an AI session."
  end
  local waiting = {}
  if empty.for_me > 0 then
    waiting[#waiting + 1] = ("%d for you"):format(empty.for_me)
  end
  if empty.waiting > 0 then
    waiting[#waiting + 1] = ("%d blocked"):format(empty.waiting)
  end
  if empty.blocked_status > 0 then
    waiting[#waiting + 1] = ("%d marked blocked with nothing blocking"):format(empty.blocked_status)
  end
  if empty.parked > 0 then
    waiting[#waiting + 1] = ("%d parked"):format(empty.parked)
  end
  return "Nothing can be started. Still open: "
    .. (#waiting > 0 and table.concat(waiting, ", ") or "see the list")
    .. "."
end

---The sentence for a plan that was just finished.
---@param id string
---@param summary? Tasks.PlanSummary
---@return string
function M.plan_closed_text(id, summary)
  local text = "Plan " .. fsio.clean(id) .. " is done"
  if summary then
    local facts = { ("%d task%s"):format(summary.tasks, summary.tasks == 1 and "" or "s") }
    if summary.days > 0 then
      local days = "estimate " .. estimate.fmt_days(summary.days) .. " d"
      if summary.n_without_effort > 0 then
        days = days .. (" (%d without effort)"):format(summary.n_without_effort)
      end
      facts[#facts + 1] = days
    end
    if summary.days_taken and summary.days_taken >= 0 then
      facts[#facts + 1] = ("finished in %d day%s"):format(
        summary.days_taken,
        summary.days_taken == 1 and "" or "s"
      )
    end
    text = text .. ": " .. table.concat(facts, ", ")
  end
  return text
end

---A short plain-language description of the next-task answer (a popup, a message).
---@param pick Tasks.NextPick
---@param done_id? string
---@param flow? { plans_closed?: string[], plan_summaries?: table<string, table> }  # What the finish did besides: plans closed.
---@return string[] lines
function M.next_message(pick, done_id, flow)
  local lines = {}
  if done_id then
    local head = "Done: " .. fsio.clean(done_id)
    if #pick.freed > 0 then
      head = head .. " \194\183 freed: " .. fsio.clean(table.concat(pick.freed, ", "))
    end
    lines[#lines + 1] = head
  end
  for _, plan_id in ipairs(flow and flow.plans_closed or {}) do
    lines[#lines + 1] =
      M.plan_closed_text(plan_id, flow and flow.plan_summaries and flow.plan_summaries[plan_id])
  end
  local t = pick.task
  if t then
    local facts = {}
    if t.prio then
      facts[#facts + 1] = "P" .. t.prio
    end
    if t.effort then
      facts[#facts + 1] = t.effort
    end
    if t.value then
      facts[#facts + 1] = "value " .. t.value
    end
    local roi = model.roi(t)
    if roi then
      facts[#facts + 1] = ("roi %.1f"):format(roi)
    end
    lines[#lines + 1] = ("Next: %s -- %s%s"):format(
      fsio.clean(t.id),
      fsio.clean(t.title),
      #facts > 0 and (" (" .. table.concat(facts, " \194\183 ") .. ")") or ""
    )
    local why = {
      freed = "freed by the task you just finished",
      area = "same area",
      vault = "elsewhere in the vault",
    }
    lines[#lines + 1] = "Why: " .. (why[pick.reason or ""] or "best ready task")
  else
    local empty = pick.empty
    lines[#lines + 1] = empty and M.empty_text(empty) or "Nothing to start."
    if empty and empty.area_empty then
      lines[#lines + 1] = "No open task left in that area."
    end
  end
  if #pick.cdx > 0 then
    local names = {}
    for _, ai_task in ipairs(pick.cdx) do
      names[#names + 1] = ai_task.id
    end
    lines[#lines + 1] = "An AI session could take: " .. fsio.clean(table.concat(names, ", "))
  end
  return lines
end

return M
